version: '2'
services:
  database:
    container_name: symfony-database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: php_docker
      MYSQL_USER: php
      MYSQL_PASSWORD: php
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  phpfpm:
    build: ./fpm
    container_name: "php8-phpfpm"
    volumes:
      - ./php-app:/var/www/php-app
      - ./fpm/php.ini:/opt/bitnami/php/etc/php.ini
    depends_on:
      - database
  nginx:
    image: nginx
    container_name: "php8-nginx"
    ports:
      - 80:80
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./php-app:/var/www/php-app
    depends_on:
      - phpfpm
      - database